const testData = {
  information: {
    vegetarian: false,
    vegan: false,
    glutenFree: true,
    dairyFree: true,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    weightWatcherSmartPoints: 4,
    gaps: "no",
    lowFodmap: false,
    aggregateLikes: 1,
    spoonacularScore: 68,
    healthScore: 28,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 125.96,
    extendedIngredients: [
      {
        id: 1005062,
        aisle: "Meat",
        image: "chicken-breasts.png",
        consistency: "solid",
        name: "bone in chicken breast",
        nameClean: "bone in chicken breast",
        original: "1 chicken breast, bone in, skin on",
        originalString: "1 chicken breast, bone in, skin on",
        originalName: "chicken breast, bone in, skin on",
        amount: 1,
        unit: "",
        meta: ["bone in", ", skin on"],
        metaInformation: ["bone in", ", skin on"],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 11246,
        aisle: "Produce",
        image: "leeks.jpg",
        consistency: "solid",
        name: "leek",
        nameClean: "leek",
        original:
          "1 large leek, thinly sliced (make sure you thoroughly wash your leek! Lots of sand!)",
        originalString:
          "1 large leek, thinly sliced (make sure you thoroughly wash your leek! Lots of sand!)",
        originalName:
          "leek, thinly sliced (make sure you thoroughly wash your leek! Lots of sand!)",
        amount: 1,
        unit: "large",
        meta: [
          "thinly sliced",
          "(make sure you thoroughly wash your leek! Lots of sand!)",
        ],
        metaInformation: [
          "thinly sliced",
          "(make sure you thoroughly wash your leek! Lots of sand!)",
        ],
        measures: {
          us: {
            amount: 1,
            unitShort: "large",
            unitLong: "large",
          },
          metric: {
            amount: 1,
            unitShort: "large",
            unitLong: "large",
          },
        },
      },
      {
        id: 11282,
        aisle: "Produce",
        image: "brown-onion.png",
        consistency: "solid",
        name: "onion",
        nameClean: "onion",
        original: "1 medium onion, diced",
        originalString: "1 medium onion, diced",
        originalName: "onion, diced",
        amount: 1,
        unit: "medium",
        meta: ["diced"],
        metaInformation: ["diced"],
        measures: {
          us: {
            amount: 1,
            unitShort: "medium",
            unitLong: "medium",
          },
          metric: {
            amount: 1,
            unitShort: "medium",
            unitLong: "medium",
          },
        },
      },
      {
        id: 11215,
        aisle: "Produce",
        image: "garlic.png",
        consistency: "solid",
        name: "garlic",
        nameClean: "garlic",
        original: "3 medium garlic gloves, minced",
        originalString: "3 medium garlic gloves, minced",
        originalName: "garlic gloves, minced",
        amount: 3,
        unit: "medium",
        meta: ["minced"],
        metaInformation: ["minced"],
        measures: {
          us: {
            amount: 3,
            unitShort: "medium",
            unitLong: "mediums",
          },
          metric: {
            amount: 3,
            unitShort: "medium",
            unitLong: "mediums",
          },
        },
      },
      {
        id: 11124,
        aisle: "Produce",
        image: "sliced-carrot.png",
        consistency: "solid",
        name: "carrots",
        nameClean: "carrot",
        original: "2 small carrots, diced",
        originalString: "2 small carrots, diced",
        originalName: "carrots, diced",
        amount: 2,
        unit: "small",
        meta: ["diced"],
        metaInformation: ["diced"],
        measures: {
          us: {
            amount: 2,
            unitShort: "small",
            unitLong: "smalls",
          },
          metric: {
            amount: 2,
            unitShort: "small",
            unitLong: "smalls",
          },
        },
      },
      {
        id: 4053,
        aisle: "Oil, Vinegar, Salad Dressing",
        image: "olive-oil.jpg",
        consistency: "liquid",
        name: "olive oil",
        nameClean: "olive oil",
        original: "2 tablespoons olive oil",
        originalString: "2 tablespoons olive oil",
        originalName: "olive oil",
        amount: 2,
        unit: "tablespoons",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
          metric: {
            amount: 2,
            unitShort: "Tbsps",
            unitLong: "Tbsps",
          },
        },
      },
      {
        id: 2004,
        aisle: "Spices and Seasonings",
        image: "bay-leaves.jpg",
        consistency: "solid",
        name: "bay leaf",
        nameClean: "bay leaves",
        original: "1 bay leaf",
        originalString: "1 bay leaf",
        originalName: "bay leaf",
        amount: 1,
        unit: "",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 2042,
        aisle: "Spices and Seasonings",
        image: "thyme.jpg",
        consistency: "solid",
        name: "dried thyme",
        nameClean: "dried thyme",
        original: "1 teaspoon dried thyme",
        originalString: "1 teaspoon dried thyme",
        originalName: "dried thyme",
        amount: 1,
        unit: "teaspoon",
        meta: ["dried"],
        metaInformation: ["dried"],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 1032009,
        aisle: "Spices and Seasonings",
        image: "red-pepper-flakes.jpg",
        consistency: "solid",
        name: "chili flakes",
        nameClean: "red pepper flakes",
        original: "1 teaspoon chili pepper flakes (optional)",
        originalString: "1 teaspoon chili pepper flakes (optional)",
        originalName: "chili pepper flakes (optional)",
        amount: 1,
        unit: "teaspoon",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 20040,
        aisle: "Pasta and Rice",
        image: "uncooked-brown-rice.png",
        consistency: "solid",
        name: "brown rice",
        nameClean: "brown rice",
        original: "1/2 cup of brown basmati rice*",
        originalString: "1/2 cup of brown basmati rice*",
        originalName: "brown basmati rice",
        amount: 0.5,
        unit: "cup",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1006970,
        aisle: "Canned and Jarred",
        image: "broth.jpg",
        consistency: "solid",
        name: "low sodium chicken stock",
        nameClean: "low sodium chicken stock",
        original: "5 cups of low-sodium chicken stock",
        originalString: "5 cups of low-sodium chicken stock",
        originalName: "low-sodium chicken stock",
        amount: 5,
        unit: "cups",
        meta: ["low-sodium"],
        metaInformation: ["low-sodium"],
        measures: {
          us: {
            amount: 5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 1.183,
            unitShort: "l",
            unitLong: "liters",
          },
        },
      },
      {
        id: 11266,
        aisle: "Produce",
        image: "mushrooms.png",
        consistency: "solid",
        name: "baby bella mushrooms",
        nameClean: "crimini mushrooms",
        original: "1 cup of baby Bella mushrooms, sliced",
        originalString: "1 cup of baby Bella mushrooms, sliced",
        originalName: "baby Bella mushrooms, sliced",
        amount: 1,
        unit: "cup",
        meta: ["sliced"],
        metaInformation: ["sliced"],
        measures: {
          us: {
            amount: 1,
            unitShort: "cup",
            unitLong: "cup",
          },
          metric: {
            amount: 236.588,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 11304,
        aisle: "Produce",
        image: "peas.jpg",
        consistency: "solid",
        name: "green peas",
        nameClean: "petite peas",
        original: "1/2 cup of green peas",
        originalString: "1/2 cup of green peas",
        originalName: "green peas",
        amount: 0.5,
        unit: "cup",
        meta: ["green"],
        metaInformation: ["green"],
        measures: {
          us: {
            amount: 0.5,
            unitShort: "cups",
            unitLong: "cups",
          },
          metric: {
            amount: 118.294,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 1102047,
        aisle: "Spices and Seasonings",
        image: "salt-and-pepper.jpg",
        consistency: "solid",
        name: "Salt & Pepper",
        nameClean: "salt and pepper",
        original: "salt/pepper",
        originalString: "salt/pepper",
        originalName: "salt/pepper",
        amount: 1,
        unit: "serving",
        meta: [],
        metaInformation: [],
        measures: {
          us: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
          metric: {
            amount: 1,
            unitShort: "serving",
            unitLong: "serving",
          },
        },
      },
    ],
    id: 637904,
    title: "Chicken and Leek Porridge",
    readyInMinutes: 45,
    servings: 6,
    sourceUrl:
      "https://www.foodista.com/recipe/XSQQFQVH/chicken-and-leek-porridge",
    image: "https://spoonacular.com/recipeImages/637904-556x370.jpg",
    imageType: "jpg",
    summary:
      'Chicken and Leek Porridge might be a good recipe to expand your breakfast recipe box. One portion of this dish contains roughly <b>13g of protein</b>, <b>7g of fat</b>, and a total of <b>204 calories</b>. This gluten free and dairy free recipe serves 6 and costs <b>$1.26 per serving</b>. From preparation to the plate, this recipe takes around <b>around 45 minutes</b>. 1 person were impressed by this recipe. A mixture of garlic gloves, olive oil, carrots, and a handful of other ingredients are all it takes to make this recipe so yummy. It is brought to you by Foodista. Taking all factors into account, this recipe <b>earns a spoonacular score of 67%</b>, which is solid. If you like this recipe, take a look at these similar recipes: <a href="https://spoonacular.com/recipes/chicken-porridge-638257">Chicken Porridge</a>, <a href="https://spoonacular.com/recipes/chicken-congee-rice-porridge-233690">Chicken Congee (Rice Porridge)</a>, and <a href="https://spoonacular.com/recipes/korean-dak-juk-chicken-porridge-649045">Korean Dak Juk (Chicken Porridge)</a>.',
    cuisines: [],
    dishTypes: ["morning meal", "brunch", "breakfast"],
    diets: ["gluten free", "dairy free"],
    occasions: [],
    winePairing: {
      pairedWines: [],
      pairingText: "",
      productMatches: [],
    },
    instructions:
      "Pre-heat oven to 350 degrees.\nRub your chicken with 1 tablespoon of olive oil and sprinkle on 1 tsp of salt and  a tsp of ground black pepper.\nPut in oven for 35 minutes.  Remove from oven and let sit.  (if you dont have time to cook your chicken, you can buy a rotisserie from the store and shred about a 1  cup of the chicken.)\nUsing a large soup pot (large creuset is nice), turn  heat on to medium.  5. Once pot is hot, add the 1-tablespoon of olive oil, the onions, carrots  and the leek.\nAdd 1 tsp of salt and  a tsp of ground black pepper.\nOnce the onions are translucent, add the garlic and stir for 1-2 minutes.\nAdd the bay leaf, thyme and chili pepper flakes (if using).  Stir for 1-2 minutes.\nThen add the rice.  Stir the rice until well coated with oil and well combined with other ingredients.\nAdd 5 cups of the chicken stock.  Bring to a boil, then reduce to a simmer and put the cover on the pot.  Stirring occasionally (so the rice doesnt settle), let simmer for about 45 minutes.\nIn the meantime, shred your roasted chicken breast into bite-sized pieces.\nAfter 45 minutes, your rice should have a porridge-like consistency (slightly more liquid present than in a risotto, but not as much as a soup).  13. Add your shredded chicken, mushrooms and peas.   Stir and cook for another 3-5 minutes.\nServe with a little parsley on top and enjoy hot!\nThe basmati rice is not nearly as starchy as a shorter grain rice, so you wont fully get a porridge like consistency here if you use it.  However, I use it in my recipe because it has greater nutritional benefits.",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Pre-heat oven to 350 degrees.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
          {
            number: 2,
            step: "Rub your chicken with 1 tablespoon of olive oil and sprinkle on 1 tsp of salt and  a tsp of ground black pepper.",
            ingredients: [
              {
                id: 1002030,
                name: "ground black pepper",
                localizedName: "ground black pepper",
                image: "pepper.jpg",
              },
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 5006,
                name: "whole chicken",
                localizedName: "whole chicken",
                image: "whole-chicken.jpg",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
              {
                id: 1012034,
                name: "dry seasoning rub",
                localizedName: "dry seasoning rub",
                image: "seasoning.png",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Put in oven for 35 minutes.",
            ingredients: [],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
            length: {
              number: 35,
              unit: "minutes",
            },
          },
          {
            number: 4,
            step: "Remove from oven and let sit.  (if you dont have time to cook your chicken, you can buy a rotisserie from the store and shred about a 1  cup of the chicken.)",
            ingredients: [
              {
                id: 5006,
                name: "whole chicken",
                localizedName: "whole chicken",
                image: "whole-chicken.jpg",
              },
            ],
            equipment: [
              {
                id: 404784,
                name: "oven",
                localizedName: "oven",
                image: "oven.jpg",
              },
            ],
          },
          {
            number: 5,
            step: "Using a large soup pot (large creuset is nice), turn  heat on to medium.",
            ingredients: [
              {
                id: 0,
                name: "soup",
                localizedName: "soup",
                image: "",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
          {
            number: 6,
            step: "Once pot is hot, add the 1-tablespoon of olive oil, the onions, carrots  and the leek.",
            ingredients: [
              {
                id: 4053,
                name: "olive oil",
                localizedName: "olive oil",
                image: "olive-oil.jpg",
              },
              {
                id: 11124,
                name: "carrot",
                localizedName: "carrot",
                image: "sliced-carrot.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
              {
                id: 11246,
                name: "leek",
                localizedName: "leek",
                image: "leeks.jpg",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
          },
          {
            number: 7,
            step: "Add 1 tsp of salt and  a tsp of ground black pepper.",
            ingredients: [
              {
                id: 1002030,
                name: "ground black pepper",
                localizedName: "ground black pepper",
                image: "pepper.jpg",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 8,
            step: "Once the onions are translucent, add the garlic and stir for 1-2 minutes.",
            ingredients: [
              {
                id: 11215,
                name: "garlic",
                localizedName: "garlic",
                image: "garlic.png",
              },
              {
                id: 11282,
                name: "onion",
                localizedName: "onion",
                image: "brown-onion.png",
              },
            ],
            equipment: [],
            length: {
              number: 2,
              unit: "minutes",
            },
          },
          {
            number: 9,
            step: "Add the bay leaf, thyme and chili pepper flakes (if using).  Stir for 1-2 minutes.",
            ingredients: [
              {
                id: 11819,
                name: "chili pepper",
                localizedName: "chili pepper",
                image: "red-chili.jpg",
              },
              {
                id: 2004,
                name: "bay leaves",
                localizedName: "bay leaves",
                image: "bay-leaves.jpg",
              },
              {
                id: 2049,
                name: "thyme",
                localizedName: "thyme",
                image: "thyme.jpg",
              },
            ],
            equipment: [],
            length: {
              number: 2,
              unit: "minutes",
            },
          },
          {
            number: 10,
            step: "Then add the rice.  Stir the rice until well coated with oil and well combined with other ingredients.",
            ingredients: [
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
              {
                id: 4582,
                name: "cooking oil",
                localizedName: "cooking oil",
                image: "vegetable-oil.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 11,
            step: "Add 5 cups of the chicken stock.  Bring to a boil, then reduce to a simmer and put the cover on the pot.  Stirring occasionally (so the rice doesnt settle), let simmer for about 45 minutes.",
            ingredients: [
              {
                id: 6172,
                name: "chicken stock",
                localizedName: "chicken stock",
                image: "chicken-broth.png",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
            ],
            equipment: [
              {
                id: 404752,
                name: "pot",
                localizedName: "pot",
                image: "stock-pot.jpg",
              },
            ],
            length: {
              number: 45,
              unit: "minutes",
            },
          },
          {
            number: 12,
            step: "In the meantime, shred your roasted chicken breast into bite-sized pieces.",
            ingredients: [
              {
                id: 5064,
                name: "cooked chicken breast",
                localizedName: "cooked chicken breast",
                image: "cooked-chicken-breast.png",
              },
            ],
            equipment: [],
          },
          {
            number: 13,
            step: "After 45 minutes, your rice should have a porridge-like consistency (slightly more liquid present than in a risotto, but not as much as a soup).  1",
            ingredients: [
              {
                id: 0,
                name: "hot cereal",
                localizedName: "hot cereal",
                image: "",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
              {
                id: 0,
                name: "soup",
                localizedName: "soup",
                image: "",
              },
            ],
            equipment: [],
            length: {
              number: 45,
              unit: "minutes",
            },
          },
          {
            number: 14,
            step: "Add your shredded chicken, mushrooms and peas.   Stir and cook for another 3-5 minutes.",
            ingredients: [
              {
                id: 1005114,
                name: "shredded chicken",
                localizedName: "shredded chicken",
                image: "rotisserie-chicken.png",
              },
              {
                id: 11260,
                name: "mushrooms",
                localizedName: "mushrooms",
                image: "mushrooms.png",
              },
              {
                id: 11304,
                name: "peas",
                localizedName: "peas",
                image: "peas.jpg",
              },
            ],
            equipment: [],
            length: {
              number: 5,
              unit: "minutes",
            },
          },
          {
            number: 15,
            step: "Serve with a little parsley on top and enjoy hot!",
            ingredients: [
              {
                id: 11297,
                name: "parsley",
                localizedName: "parsley",
                image: "parsley.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 16,
            step: "The basmati rice is not nearly as starchy as a shorter grain rice, so you wont fully get a porridge like consistency here if you use it.  However, I use it in my recipe because it has greater nutritional benefits.",
            ingredients: [
              {
                id: 10020444,
                name: "basmati rice",
                localizedName: "basmati rice",
                image: "rice-white-long-grain-or-basmatii-cooked.jpg",
              },
              {
                id: 0,
                name: "hot cereal",
                localizedName: "hot cereal",
                image: "",
              },
              {
                id: 0,
                name: "grains",
                localizedName: "grains",
                image: "",
              },
              {
                id: 20444,
                name: "rice",
                localizedName: "rice",
                image: "uncooked-white-rice.png",
              },
            ],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularSourceUrl:
      "https://spoonacular.com/chicken-and-leek-porridge-637904",
  },
  instructions: [
    {
      number: 1,
      step: "Pre-heat oven to 350 degrees.",
      ingredients: [],
      equipment: [
        {
          id: 404784,
          name: "oven",
          localizedName: "oven",
          image: "oven.jpg",
        },
      ],
    },
    {
      number: 2,
      step: "Rub your chicken with 1 tablespoon of olive oil and sprinkle on 1 tsp of salt and  a tsp of ground black pepper.",
      ingredients: [
        {
          id: 1002030,
          name: "ground black pepper",
          localizedName: "ground black pepper",
          image: "pepper.jpg",
        },
        {
          id: 4053,
          name: "olive oil",
          localizedName: "olive oil",
          image: "olive-oil.jpg",
        },
        {
          id: 5006,
          name: "whole chicken",
          localizedName: "whole chicken",
          image: "whole-chicken.jpg",
        },
        {
          id: 2047,
          name: "salt",
          localizedName: "salt",
          image: "salt.jpg",
        },
        {
          id: 1012034,
          name: "dry seasoning rub",
          localizedName: "dry seasoning rub",
          image: "seasoning.png",
        },
      ],
      equipment: [],
    },
    {
      number: 3,
      step: "Put in oven for 35 minutes.",
      ingredients: [],
      equipment: [
        {
          id: 404784,
          name: "oven",
          localizedName: "oven",
          image: "oven.jpg",
        },
      ],
      length: {
        number: 35,
        unit: "minutes",
      },
    },
    {
      number: 4,
      step: "Remove from oven and let sit.  (if you dont have time to cook your chicken, you can buy a rotisserie from the store and shred about a 1  cup of the chicken.)",
      ingredients: [
        {
          id: 5006,
          name: "whole chicken",
          localizedName: "whole chicken",
          image: "whole-chicken.jpg",
        },
      ],
      equipment: [
        {
          id: 404784,
          name: "oven",
          localizedName: "oven",
          image: "oven.jpg",
        },
      ],
    },
    {
      number: 5,
      step: "Using a large soup pot (large creuset is nice), turn  heat on to medium.",
      ingredients: [
        {
          id: 0,
          name: "soup",
          localizedName: "soup",
          image: "",
        },
      ],
      equipment: [
        {
          id: 404752,
          name: "pot",
          localizedName: "pot",
          image: "stock-pot.jpg",
        },
      ],
    },
    {
      number: 6,
      step: "Once pot is hot, add the 1-tablespoon of olive oil, the onions, carrots  and the leek.",
      ingredients: [
        {
          id: 4053,
          name: "olive oil",
          localizedName: "olive oil",
          image: "olive-oil.jpg",
        },
        {
          id: 11124,
          name: "carrot",
          localizedName: "carrot",
          image: "sliced-carrot.png",
        },
        {
          id: 11282,
          name: "onion",
          localizedName: "onion",
          image: "brown-onion.png",
        },
        {
          id: 11246,
          name: "leek",
          localizedName: "leek",
          image: "leeks.jpg",
        },
      ],
      equipment: [
        {
          id: 404752,
          name: "pot",
          localizedName: "pot",
          image: "stock-pot.jpg",
        },
      ],
    },
    {
      number: 7,
      step: "Add 1 tsp of salt and  a tsp of ground black pepper.",
      ingredients: [
        {
          id: 1002030,
          name: "ground black pepper",
          localizedName: "ground black pepper",
          image: "pepper.jpg",
        },
        {
          id: 2047,
          name: "salt",
          localizedName: "salt",
          image: "salt.jpg",
        },
      ],
      equipment: [],
    },
    {
      number: 8,
      step: "Once the onions are translucent, add the garlic and stir for 1-2 minutes.",
      ingredients: [
        {
          id: 11215,
          name: "garlic",
          localizedName: "garlic",
          image: "garlic.png",
        },
        {
          id: 11282,
          name: "onion",
          localizedName: "onion",
          image: "brown-onion.png",
        },
      ],
      equipment: [],
      length: {
        number: 2,
        unit: "minutes",
      },
    },
    {
      number: 9,
      step: "Add the bay leaf, thyme and chili pepper flakes (if using).  Stir for 1-2 minutes.",
      ingredients: [
        {
          id: 11819,
          name: "chili pepper",
          localizedName: "chili pepper",
          image: "red-chili.jpg",
        },
        {
          id: 2004,
          name: "bay leaves",
          localizedName: "bay leaves",
          image: "bay-leaves.jpg",
        },
        {
          id: 2049,
          name: "thyme",
          localizedName: "thyme",
          image: "thyme.jpg",
        },
      ],
      equipment: [],
      length: {
        number: 2,
        unit: "minutes",
      },
    },
    {
      number: 10,
      step: "Then add the rice.  Stir the rice until well coated with oil and well combined with other ingredients.",
      ingredients: [
        {
          id: 20444,
          name: "rice",
          localizedName: "rice",
          image: "uncooked-white-rice.png",
        },
        {
          id: 4582,
          name: "cooking oil",
          localizedName: "cooking oil",
          image: "vegetable-oil.jpg",
        },
      ],
      equipment: [],
    },
    {
      number: 11,
      step: "Add 5 cups of the chicken stock.  Bring to a boil, then reduce to a simmer and put the cover on the pot.  Stirring occasionally (so the rice doesnt settle), let simmer for about 45 minutes.",
      ingredients: [
        {
          id: 6172,
          name: "chicken stock",
          localizedName: "chicken stock",
          image: "chicken-broth.png",
        },
        {
          id: 20444,
          name: "rice",
          localizedName: "rice",
          image: "uncooked-white-rice.png",
        },
      ],
      equipment: [
        {
          id: 404752,
          name: "pot",
          localizedName: "pot",
          image: "stock-pot.jpg",
        },
      ],
      length: {
        number: 45,
        unit: "minutes",
      },
    },
    {
      number: 12,
      step: "In the meantime, shred your roasted chicken breast into bite-sized pieces.",
      ingredients: [
        {
          id: 5064,
          name: "cooked chicken breast",
          localizedName: "cooked chicken breast",
          image: "cooked-chicken-breast.png",
        },
      ],
      equipment: [],
    },
    {
      number: 13,
      step: "After 45 minutes, your rice should have a porridge-like consistency (slightly more liquid present than in a risotto, but not as much as a soup).  1",
      ingredients: [
        {
          id: 0,
          name: "hot cereal",
          localizedName: "hot cereal",
          image: "",
        },
        {
          id: 20444,
          name: "rice",
          localizedName: "rice",
          image: "uncooked-white-rice.png",
        },
        {
          id: 0,
          name: "soup",
          localizedName: "soup",
          image: "",
        },
      ],
      equipment: [],
      length: {
        number: 45,
        unit: "minutes",
      },
    },
    {
      number: 14,
      step: "Add your shredded chicken, mushrooms and peas.   Stir and cook for another 3-5 minutes.",
      ingredients: [
        {
          id: 1005114,
          name: "shredded chicken",
          localizedName: "shredded chicken",
          image: "rotisserie-chicken.png",
        },
        {
          id: 11260,
          name: "mushrooms",
          localizedName: "mushrooms",
          image: "mushrooms.png",
        },
        {
          id: 11304,
          name: "peas",
          localizedName: "peas",
          image: "peas.jpg",
        },
      ],
      equipment: [],
      length: {
        number: 5,
        unit: "minutes",
      },
    },
    {
      number: 15,
      step: "Serve with a little parsley on top and enjoy hot!",
      ingredients: [
        {
          id: 11297,
          name: "parsley",
          localizedName: "parsley",
          image: "parsley.jpg",
        },
      ],
      equipment: [],
    },
    {
      number: 16,
      step: "The basmati rice is not nearly as starchy as a shorter grain rice, so you wont fully get a porridge like consistency here if you use it.  However, I use it in my recipe because it has greater nutritional benefits.",
      ingredients: [
        {
          id: 10020444,
          name: "basmati rice",
          localizedName: "basmati rice",
          image: "rice-white-long-grain-or-basmatii-cooked.jpg",
        },
        {
          id: 0,
          name: "hot cereal",
          localizedName: "hot cereal",
          image: "",
        },
        {
          id: 0,
          name: "grains",
          localizedName: "grains",
          image: "",
        },
        {
          id: 20444,
          name: "rice",
          localizedName: "rice",
          image: "uncooked-white-rice.png",
        },
      ],
      equipment: [],
    },
  ],
  nutrition: {
    calories: "203k",
    carbs: "22g",
    fat: "7g",
    protein: "13g",
    bad: [
      {
        title: "Calories",
        amount: "203k",
        indented: false,
        percentOfDailyNeeds: 10.19,
      },
      {
        title: "Fat",
        amount: "7g",
        indented: false,
        percentOfDailyNeeds: 11.21,
      },
      {
        title: "Saturated Fat",
        amount: "1g",
        indented: true,
        percentOfDailyNeeds: 8.1,
      },
      {
        title: "Carbohydrates",
        amount: "22g",
        indented: false,
        percentOfDailyNeeds: 7.62,
      },
      {
        title: "Sugar",
        amount: "3g",
        indented: true,
        percentOfDailyNeeds: 3.71,
      },
      {
        title: "Cholesterol",
        amount: "19mg",
        indented: false,
        percentOfDailyNeeds: 6.43,
      },
      {
        title: "Sodium",
        amount: "149mg",
        indented: false,
        percentOfDailyNeeds: 6.49,
      },
    ],
    good: [
      {
        title: "Protein",
        amount: "13g",
        indented: false,
        percentOfDailyNeeds: 26.42,
      },
      {
        title: "Vitamin A",
        amount: "3239IU",
        indented: false,
        percentOfDailyNeeds: 64.8,
      },
      {
        title: "Manganese",
        amount: "0.83mg",
        indented: false,
        percentOfDailyNeeds: 41.39,
      },
      {
        title: "Vitamin B3",
        amount: "7mg",
        indented: false,
        percentOfDailyNeeds: 37.65,
      },
      {
        title: "Vitamin B6",
        amount: "0.47mg",
        indented: false,
        percentOfDailyNeeds: 23.29,
      },
      {
        title: "Phosphorus",
        amount: "211mg",
        indented: false,
        percentOfDailyNeeds: 21.15,
      },
      {
        title: "Selenium",
        amount: "13µg",
        indented: false,
        percentOfDailyNeeds: 19.32,
      },
      {
        title: "Vitamin K",
        amount: "18µg",
        indented: false,
        percentOfDailyNeeds: 17.47,
      },
      {
        title: "Potassium",
        amount: "527mg",
        indented: false,
        percentOfDailyNeeds: 15.06,
      },
      {
        title: "Copper",
        amount: "0.28mg",
        indented: false,
        percentOfDailyNeeds: 13.77,
      },
      {
        title: "Vitamin C",
        amount: "9mg",
        indented: false,
        percentOfDailyNeeds: 11.97,
      },
      {
        title: "Magnesium",
        amount: "46mg",
        indented: false,
        percentOfDailyNeeds: 11.69,
      },
      {
        title: "Vitamin B2",
        amount: "0.2mg",
        indented: false,
        percentOfDailyNeeds: 11.49,
      },
      {
        title: "Vitamin B1",
        amount: "0.16mg",
        indented: false,
        percentOfDailyNeeds: 10.75,
      },
      {
        title: "Fiber",
        amount: "2g",
        indented: false,
        percentOfDailyNeeds: 9.94,
      },
      {
        title: "Iron",
        amount: "1mg",
        indented: false,
        percentOfDailyNeeds: 9.77,
      },
      {
        title: "Vitamin B5",
        amount: "0.96mg",
        indented: false,
        percentOfDailyNeeds: 9.59,
      },
      {
        title: "Folate",
        amount: "31µg",
        indented: false,
        percentOfDailyNeeds: 8,
      },
      {
        title: "Vitamin E",
        amount: "1mg",
        indented: false,
        percentOfDailyNeeds: 7.57,
      },
      {
        title: "Zinc",
        amount: "1mg",
        indented: false,
        percentOfDailyNeeds: 7.37,
      },
      {
        title: "Calcium",
        amount: "45mg",
        indented: false,
        percentOfDailyNeeds: 4.54,
      },
      {
        title: "Vitamin B12",
        amount: "0.27µg",
        indented: false,
        percentOfDailyNeeds: 4.48,
      },
    ],
    expires: 1633925405703,
    isStale: false,
  },
};

module.exports = { testData };
